mixin.feature.branding=false
mixin.perf.clear_mixin_classinfo=true
mixin.perf.model_optimizations=true
mixin.perf.faster_item_rendering=true
mixin.perf.deduplicate_climate_parameters=true
mixin.perf.deduplicate_location=true
mixin.perf.dynamic_entity_renderers=true
mixin.perf.dynamic_languages=true
mixin.perf.compact_entity_models=true
mixin.perf.compact_imposterprotochunks=true