#Indigo properties file
#Wed May 06 16:29:12 BDT 2026
ambient-occlusion-mode=hybrid
debug-compare-lighting=false
fix-exterior-vertex-lighting=true
fix-luminous-block-ambient-occlusion=true
fix-mean-light-calculation=auto
fix-smooth-lighting-offset=true
